# DataSource Config
spring:
  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tb_record_space?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 100

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

custom:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 10000000
    header: Authorization

server:
  port: 8008


shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
  cache-manager:
    principal-id-field-name: username



logging:
  level:
    com.hjw.mapper: trace
    com.hjw: debug
